### ISSUE TITLE
Is working?

### ISSUE THREAD

**Issue by rferreiroa** [picturae/OpenSeadragonMagnifier#1]
Hi, i´m trying to develop a magnifier for openseadragon. Is this working? I saw that there are some empty functions like moveRegion or resizeRegion.

Kind regards

**Comment by MindFreeze** [comment]
It mostly works. The magnifier works even with rotation but I didn't have time to finish these empty functions. The region can actually be moved when you use the magnifier box as a normal viewer but this is not intended to be the only way. You can try it out with the code from the README and you can pass options like this:

```
        var magnifier = viewer.magnifier({
            position: 'BOTTOM_RIGHT',
            defaultZoomLevel: 5,
            minZoomLevel: 1,
        });
```

The empty functions can be implemented with code very similar to https://github.com/picturae/openseadragonselection . I just don't have the time to finish this though.

**Comment by rferreiroa** [comment]
Ok! I´ll try it. Thanks for your response.

Kind regards
